spring:
  main:
    banner-mode: off

server:
  port: 9000

# Rabbit MQ
rabbitmq:
  username: guest
  password: guest
  host: localhost
  virtual-host: /
  port: 5672

# Card Status Notification
card-notification:
  exchange: card-notification-header-exchange
  header: json__TypeId__
  dead-letter-exchange: dead-letter-exchange
  message-time-to-live: 2500
  max-dead-threshold: 15
  status-changed:
    queue: card-status-changed.queue
    key: card-status-changed
